language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.6"
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.0
install:
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO
  - pip install coveralls
script:
  - coverage run --source=. runtests.py
after_success:
  - coveralls
matrix:
  exclude:
   - python: "2.7"
     env: DJANGO=2.0
